# Generated by Django 5.1.5 on 2025-02-15 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyOrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('choice_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookmodel', verbose_name='Книга')),
            ],
        ),
    ]
