# Generated by Django 5.1.5 on 2025-02-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='books/', verbose_name='загрузите фото')),
                ('title', models.CharField(max_length=150, verbose_name='укажите название книги')),
                ('description', models.TextField(blank=True, verbose_name='укажите описание книг')),
                ('price', models.PositiveIntegerField(default=300, verbose_name='укажите цену книг')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('PSYCHOLOGY', 'PSYCHOLOGY'), ('NOVEL', 'NOVEL'), ('LITERARY', 'LITERARY'), ('FANTASY', 'FANTASY')], default='NOVEL', max_length=25, verbose_name='выберите жанр')),
                ('email', models.TextField(verbose_name='укажите почту')),
                ('author', models.CharField(max_length=200, verbose_name='укажите автора')),
                ('trailer', models.URLField(verbose_name='оставьте ссылку из YOUTUBE')),
            ],
        ),
    ]
