# Generated by Django 5.1.5 on 2025-02-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmodel',
            options={'verbose_name': 'книгу', 'verbose_name_plural': 'книги'},
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='author',
            field=models.CharField(default='Исаков Иса', max_length=200, verbose_name='укажите автора'),
        ),
    ]
