# Generated by Django 5.1.5 on 2025-02-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RezkaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='bookhousemodel',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='bookhousemodel',
            name='price',
            field=models.CharField(max_length=250),
        ),
    ]
