# Generated by Django 5.1.5 on 2025-02-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_rezkamodel_alter_bookhousemodel_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MashinaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
            ],
        ),
    ]
