# Generated by Django 5.1.5 on 2025-02-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_mashinamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mashinamodel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
