# Generated by Django 5.1.5 on 2025-02-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_alter_mashinamodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mashinamodel',
            name='image',
        ),
    ]
