# Generated by Django 5.1.5 on 2025-02-12 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name': 'Одежду', 'verbose_name_plural': 'Одежды'},
        ),
    ]
