# Generated by Django 5.1.5 on 2025-02-25 17:41

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(default='+996', max_length=16)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('experience', models.IntegerField(default=0)),
                ('direction', models.CharField(choices=[('BACKEND', 'BACKEND'), ('FRONTEND', 'FRONTEND'), ('FULLSTACK', 'FULLSTACK'), ('MOBILE', 'MOBILE'), ('DEVOPS', 'DEVOPS'), ('DATA_SCIENCE', 'DATA_SCIENCE'), ('AI_ML', 'AI_ML'), ('GAME_DEV', 'GAME_DEV'), ('EMBEDDED', 'EMBEDDED'), ('CYBERSECURITY', 'CYBERSECURITY'), ('BLOCKCHAIN', 'BLOCKCHAIN')], max_length=30)),
                ('salary', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
